### ISSUE TITLE
Travis file hierarchy changes?

### ISSUE THREAD

**Issue by ryanford** [kikito/ci-with-lua#1] opened 2018-02-09 15:08 UTC
Hi, I was following this via http://lua.space/general/ci-with-lua and watched the video. When I followed the instructions as listed, Coveralls shows only ~28% coverage. Apparently it is not correctly excluding the build directory and the dependencies are reading not covered. If I change line 27 of the .travis.yml from `- luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install` to `- luacov-coveralls -e /lua_install` it works as expected.

**Comment by kikito** [comment] 2018-03-10 11:49
Hi there, I'm sorry but I can't reproduce this issue. I just pushed a new version of middleclass and coveralls reports the coverage just fine with that setting:

https://coveralls.io/github/kikito/middleclass

So I'll be closing this issue in case this was a fluke. If you keep seeing the problem, please reopen and send me a repo showing the problem so I can investigate this further.

**Closed as completed by kikito** 2018-03-10 11:49 UTC
